# Generated by Django 4.2.6 on 2023-10-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='task',
            name='datacompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
