# Generated by Django 4.2.6 on 2023-10-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_datacompleted_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datecompleted',
            new_name='datacompleted',
        ),
    ]
