# Generated by Django 5.0.3 on 2024-03-16 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_datacompleted_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='questionOne',
            new_name='c_p',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='address',
            new_name='calle_y_numero',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='education',
            new_name='colonia',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='questionTree',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='women',
            new_name='femenino',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='man',
            new_name='masculino',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='questionTwo',
            new_name='municipio',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='namecompleted',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='questionFive',
            new_name='num_casilla',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='questionFour',
            new_name='num_seccion',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='nombre_enlace',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='participacion',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
