# Generated by Django 5.0.3 on 2024-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_estado_alter_task_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edad',
            field=models.CharField(choices=[('18', '18'), ('19', '19')], default=[('18', '18'), ('19', '19')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.IntegerField(choices=[('Jal', 'Jalisco')], default='Jalisco'),
        ),
        migrations.AlterField(
            model_name='task',
            name='municipio',
            field=models.IntegerField(choices=[('gdl', 'Guadalajara')], default='Guadalajara'),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre_enlace',
            field=models.IntegerField(choices=[('Vasti_Arana', 'Vasti Arana'), ('Israel_', 'Isrrael'), ('Omar_Castellanos', 'Omar Castellanos'), ('Esther_Castellanos', 'Esther Castellanos')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='num_seccion',
            field=models.IntegerField(choices=[('1218', '1218'), ('1219', '1219'), ('1220', '1220'), ('1221', '1221'), ('1213', '1213'), ('1214', '1214'), ('1215', '1215'), ('1208', '1208'), ('1207', '1207'), ('1206', '1206'), ('1204', '1204'), ('1205', '1205'), ('1192', '1192'), ('1216', '1216'), ('1217', '1217'), ('1252', '1252'), ('1250', '1250'), ('1251', '1251'), ('1249', '1249'), ('1255', '1255'), ('0709', '0709'), ('0710', '0710'), ('0711', '0711'), ('0712', '0712'), ('0713', '0713'), ('0714', '0714'), ('0715', '0715'), ('0716', '0716'), ('0717', '0717'), ('0718', '0718'), ('0719', '0719'), ('0720', '0720'), ('0653', '0653'), ('0641', '0641'), ('0642', '0642'), ('0643', '0643'), ('0644', '0644'), ('0645', '0645'), ('0646', '0646'), ('0647', '0647'), ('0648', '0648'), ('0649', '0649'), ('0650', '0650'), ('0651', '0651'), ('0652', '0652'), ('0653', '0653'), ('0654', '0654'), ('0655', '0655'), ('0656', '0656'), ('1334', '1334'), ('1335', '1335'), ('1331', '1331'), ('1332', '1332')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='participacion',
            field=models.CharField(choices=[(1, 'Representante de Casilla'), (2, 'Representante General'), (3, 'Movilizador'), (4, 'Simpatizante')], max_length=100),
        ),
    ]
