# Generated by Django 5.0.3 on 2024-03-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(help_text='Ejemplo: yyyy-mm-dd', null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='task',
            name='edad',
            field=models.IntegerField(choices=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75')], default=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75')], help_text='Selecciona tu Edad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('Jalisco', 'Jalisco')], default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='municipio',
            field=models.CharField(choices=[('Guadalajara', 'Guadalajara')], default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre_enlace',
            field=models.CharField(choices=[('Vasti Arana', 'Vasti Arana'), ('Isrrael y Profe', 'Israel y Profe'), ('Omar Castellanos', 'Omar Castellanos'), ('Esther Castellanos', 'Esther Castellanos'), ('Cesar', 'Cesar'), ('Bere', 'Bere'), ('Caleb Lupian', 'Caleb Lupian'), ('Alonso', 'Alonso'), ('Abner Lopez', 'Abner Lopez'), ('Edgar', 'Edgar'), ('Isai', 'Isai'), ('Don Peter', 'Don Peter'), ('Adin', 'Adin')], help_text='Selecciona tu Coordinador', max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='num_seccion',
            field=models.IntegerField(choices=[(1218, '1218'), (1219, '1219'), (1220, '1220'), (1221, '1221'), (1213, '1213'), (1214, '1214'), (1215, '1215'), (1208, '1208'), (1207, '1207'), (1206, '1206'), (1204, '1204'), (1205, '1205'), (1192, '1192'), (1216, '1216'), (1217, '1217'), (1252, '1252'), (1250, '1250'), (1251, '1251'), (1249, '1249'), (1255, '1255'), (709, '0709'), (710, '0710'), (711, '0711'), (712, '0712'), (713, '0713'), (714, '0714'), (715, '0715'), (716, '0716'), (717, '0717'), (718, '0718'), (719, '0719'), (720, '0720'), (653, '0653'), (641, '0641'), (642, '0642'), (643, '0643'), (644, '0644'), (645, '0645'), (646, '0646'), (647, '0647'), (648, '0648'), (649, '0649'), (650, '0650'), (651, '0651'), (652, '0652'), (653, '0653'), (654, '0654'), (655, '0655'), (656, '0656'), (1334, '1334'), (1335, '1335'), (1331, '1331'), (1332, '1332')], help_text='Selecciona una Seccion', verbose_name='Nº de Seccion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='participacion',
            field=models.CharField(choices=[('Representante de Casilla', 'Representante de Casilla'), ('Representante General', 'Representante General'), ('Movilizador', 'Movilizador'), ('Simpatizante', 'Simpatizante')], max_length=100),
        ),
    ]
