# Generated by Django 5.0.3 on 2024-03-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_delete_user_alter_task_datecompleted_alter_task_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='num_casilla',
            field=models.CharField(blank=True, help_text='Ingresa Num de Casilla', max_length=250, verbose_name='Nº de Casilla'),
        ),
    ]
